/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mann' at '15.06.18 21:00' with Gradle 3.2.1
 *
 * @author mann, @date 15.06.18 21:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
